# Generated by Django 5.0.1 on 2026-02-04 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billings.billing'),
        ),
    ]
