# Generated by Django 5.0.1 on 2026-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_billing_source_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Partial Payment', 'Partial Payment'), ('Delivered', 'Delivered'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
