# Generated by Django 5.0.1 on 2026-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_scheduledemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_type',
            field=models.CharField(choices=[('downpayment', '50% Downpayment'), ('full', 'Full Payment')], default='downpayment', max_length=20),
        ),
    ]
