# Generated by Django 5.0.1 on 2026-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_billing_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
