# Generated by Django 5.0.1 on 2026-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_billing_delivery_date_billing_po_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='attention_person',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
