# Generated by Django 5.0.1 on 2026-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_billing_attention_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='vat_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
