# Generated by Django 5.0.1 on 2026-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cover_letter_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_letter_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_letter_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_letter_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_letter_recipient_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
