# Generated by Django 5.0.1 on 2026-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_scheduledquotationemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/reference_images/'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/item_images/'),
        ),
    ]
