# Generated by Django 5.0.1 on 2026-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation_reference_image_quotationitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='creator_signature',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/signatures/'),
        ),
    ]
