# Generated by Django 5.0.1 on 2026-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, choices=[('fabric', 'Fabric'), ('accessories', 'Accessories'), ('packaging', 'Packaging'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
